version: '3.8'

services:
  # Redis for Dapr components
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # Zipkin for tracing
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  # Dapr Placement for actor distribution
  placement:
    image: "daprio/dapr:latest"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"

  # GitHub MCP Server
  github-mcp:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.github-mcp
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - placement
    # Dapr sidecar
    deploy:
      replicas: 1
    volumes:
      - ../components:/components

  # Slack MCP Server
  slack-mcp:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.slack-mcp
    ports:
      - "8003:8003"
    depends_on:
      - redis
      - placement
    # Dapr sidecar
    deploy:
      replicas: 1
    volumes:
      - ../components:/components

  # Jira MCP Server
  jira-mcp:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.jira-mcp
    ports:
      - "8004:8004"
    depends_on:
      - redis
      - placement
    # Dapr sidecar
    deploy:
      replicas: 1
    volumes:
      - ../components:/components

  # Chatbot Service
  chatbot:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.chatbot
    ports:
      - "8002:8002"
    environment:
      - GITHUB_MCP_URL=http://github-mcp:8001
      - SLACK_MCP_URL=http://slack-mcp:8003
      - JIRA_MCP_URL=http://jira-mcp:8004
      - GROQ_API_KEY=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
    depends_on:
      - github-mcp
      - slack-mcp
      - jira-mcp
      - redis
      - placement
    # Dapr sidecar
    deploy:
      replicas: 1
    volumes:
      - ../components:/components

  # Frontend
  frontend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - chatbot
    environment:
      - REACT_APP_CHATBOT_URL=http://localhost:8002
      - REACT_APP_GITHUB_MCP_URL=http://localhost:8001
      - REACT_APP_SLACK_MCP_URL=http://localhost:8003
      - REACT_APP_JIRA_MCP_URL=http://localhost:8004 